# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupthree', '0002_groupthree_data'),
        ('groupthree', '0002_auto_20180122_2344'),
    ]

    operations = [
    ]
